### ISSUE TITLE
Add more features to pricing grid

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/rcp-site-child#18]
The features listed in the pricing grid should include more options, just for the psychological aspect:
![screen shot 2015-10-02 at 11 29 59 am](https://cloud.githubusercontent.com/assets/1034109/10251797/fdb35bc8-68f8-11e5-84ed-e19fe1354725.png)

Thoughts on what to add? Maybe the same ones highlighted in the features section of the home page?

**Comment by sumobi** [comment]
:+1: I'll add some and see how they look

**Comment by sumobi** [comment]
@pippinsplugins It just doesn't feel right adding "discount codes", "reports", "Unlimited Subscription Packages" etc for each. We'd really have to list every single feature or someone might scan the list and go, oh it doesn't have feature X, and leave. Not to mention it pushes the purchase buttons further down the page.

It works well for sites like OptinMonster (http://optinmonster.com/pricing/) where there are actually different features based on the license but I can't see it working well in our case. Do you have any ideas?

Since each license has the exact same features, why don't we just include an "All features included" link and open a modal with a list of all features. We can pull the features from a dedicated features page (which we don't have yet but would be a good idea IMO).

**Comment by sumobi** [comment]
related, I've added icons to the pricing buttons to make it more obvious that it is an external purchase: 
![screen shot 2015-10-04 at 4 28 18 pm](https://cloud.githubusercontent.com/assets/52581/10266292/084cacca-6ab5-11e5-9c67-0b72a5f9d29b.png)

**Comment by pippinsplugins** [comment]
I like the icons.

All features included sounds good

**Comment by sumobi** [comment]
Done. Leaving this issue open to remind me to build a features page.

**Comment by sumobi** [comment]
Actually, will create new issue.
